# Generated by Django 2.0 on 2021-04-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Integrates',
        ),
        migrations.AddField(
            model_name='product',
            name='Ingredients',
            field=models.CharField(default='abc,xyz,uewyvfukerybvfrei', max_length=5000),
        ),
        migrations.AlterField(
            model_name='product',
            name='Detail',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='product',
            name='Keywords',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductDescription',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='product',
            name='Status',
            field=models.CharField(max_length=500),
        ),
    ]
