# Generated by Django 2.0 on 2021-04-13 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210413_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Ingredients',
            new_name='Integrates',
        ),
    ]
